### ISSUE TITLE
env 구조 변경

### ISSUE THREAD

**Issue by chlehdwon** [sparcs-kaist/taxiSampleGenerator#21]
taxi-back에서 submodule로 부른 taxiSampleGenerator을 github action에서 실행시키기 위해 env 구조를 변경합니다.
(아니라면 taxi-back security 정보에 parameter들을 다 넣어주어야 함)
DB_PATH를 제외하고 잘 사용하지 않는 parameter들을 env에서 불러오지 않고, default 값으로 모두 코드에 고정합니다.

**Comment by 14KGun** [comment]
@chlehdwon 좋은 것 같습니다 !!
